//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness_app.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("fitness_app.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title_PerfectBody {
            get {
                return ResourceManager.GetString("Title_PerfectBody", resourceCulture);
            }
        }
        
        internal static string Subtitle_Doing {
            get {
                return ResourceManager.GetString("Subtitle_Doing", resourceCulture);
            }
        }
        
        internal static string Subtitle_Crossfit {
            get {
                return ResourceManager.GetString("Subtitle_Crossfit", resourceCulture);
            }
        }
        
        internal static string Title_Exercises {
            get {
                return ResourceManager.GetString("Title_Exercises", resourceCulture);
            }
        }
        
        internal static string Nav_Skip {
            get {
                return ResourceManager.GetString("Nav_Skip", resourceCulture);
            }
        }
        
        internal static string Nav_Next {
            get {
                return ResourceManager.GetString("Nav_Next", resourceCulture);
            }
        }
        
        internal static string Title_ShotStrong {
            get {
                return ResourceManager.GetString("Title_ShotStrong", resourceCulture);
            }
        }
        
        internal static string Title_Timeless {
            get {
                return ResourceManager.GetString("Title_Timeless", resourceCulture);
            }
        }
        
        internal static string Subtitle_WomanTraining {
            get {
                return ResourceManager.GetString("Subtitle_WomanTraining", resourceCulture);
            }
        }
        
        internal static string Title_HealthyMuscular {
            get {
                return ResourceManager.GetString("Title_HealthyMuscular", resourceCulture);
            }
        }
        
        internal static string Title_Sportswoman {
            get {
                return ResourceManager.GetString("Title_Sportswoman", resourceCulture);
            }
        }
        
        internal static string Subtitle_Standing {
            get {
                return ResourceManager.GetString("Subtitle_Standing", resourceCulture);
            }
        }
        
        internal static string ProText {
            get {
                return ResourceManager.GetString("ProText", resourceCulture);
            }
        }
        
        internal static string FitnessText {
            get {
                return ResourceManager.GetString("FitnessText", resourceCulture);
            }
        }
        
        internal static string SubtitleLine1 {
            get {
                return ResourceManager.GetString("SubtitleLine1", resourceCulture);
            }
        }
        
        internal static string SubtitleLine2 {
            get {
                return ResourceManager.GetString("SubtitleLine2", resourceCulture);
            }
        }
        
        internal static string LetsStartText {
            get {
                return ResourceManager.GetString("LetsStartText", resourceCulture);
            }
        }
    }
}
