//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness_app.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("fitness_app.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title_PerfectBody {
            get {
                return ResourceManager.GetString("Title_PerfectBody", resourceCulture);
            }
        }
        
        internal static string Subtitle_Doing {
            get {
                return ResourceManager.GetString("Subtitle_Doing", resourceCulture);
            }
        }
        
        internal static string Subtitle_Crossfit {
            get {
                return ResourceManager.GetString("Subtitle_Crossfit", resourceCulture);
            }
        }
        
        internal static string Title_Exercises {
            get {
                return ResourceManager.GetString("Title_Exercises", resourceCulture);
            }
        }
        
        internal static string Nav_Skip {
            get {
                return ResourceManager.GetString("Nav_Skip", resourceCulture);
            }
        }
        
        internal static string Nav_Next {
            get {
                return ResourceManager.GetString("Nav_Next", resourceCulture);
            }
        }
        
        internal static string Title_ShotStrong {
            get {
                return ResourceManager.GetString("Title_ShotStrong", resourceCulture);
            }
        }
        
        internal static string Title_Timeless {
            get {
                return ResourceManager.GetString("Title_Timeless", resourceCulture);
            }
        }
        
        internal static string Subtitle_WomanTraining {
            get {
                return ResourceManager.GetString("Subtitle_WomanTraining", resourceCulture);
            }
        }
        
        internal static string Title_HealthyMuscular {
            get {
                return ResourceManager.GetString("Title_HealthyMuscular", resourceCulture);
            }
        }
        
        internal static string Title_Sportswoman {
            get {
                return ResourceManager.GetString("Title_Sportswoman", resourceCulture);
            }
        }
        
        internal static string Subtitle_Standing {
            get {
                return ResourceManager.GetString("Subtitle_Standing", resourceCulture);
            }
        }
        
        internal static string ProText {
            get {
                return ResourceManager.GetString("ProText", resourceCulture);
            }
        }
        
        internal static string FitnessText {
            get {
                return ResourceManager.GetString("FitnessText", resourceCulture);
            }
        }
        
        internal static string SubtitleLine1 {
            get {
                return ResourceManager.GetString("SubtitleLine1", resourceCulture);
            }
        }
        
        internal static string SubtitleLine2 {
            get {
                return ResourceManager.GetString("SubtitleLine2", resourceCulture);
            }
        }
        
        internal static string LetsStartText {
            get {
                return ResourceManager.GetString("LetsStartText", resourceCulture);
            }
        }
        
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        internal static string HelloText1 {
            get {
                return ResourceManager.GetString("HelloText1", resourceCulture);
            }
        }
        
        internal static string HelloText2 {
            get {
                return ResourceManager.GetString("HelloText2", resourceCulture);
            }
        }
        
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        internal static string OrLoginWith {
            get {
                return ResourceManager.GetString("OrLoginWith", resourceCulture);
            }
        }
        
        internal static string GoogleButton {
            get {
                return ResourceManager.GetString("GoogleButton", resourceCulture);
            }
        }
        
        internal static string FacebookButton {
            get {
                return ResourceManager.GetString("FacebookButton", resourceCulture);
            }
        }
        
        internal static string NoAccountText {
            get {
                return ResourceManager.GetString("NoAccountText", resourceCulture);
            }
        }
        
        internal static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        internal static string CreateAccountTitle {
            get {
                return ResourceManager.GetString("CreateAccountTitle", resourceCulture);
            }
        }
        
        internal static string CredentialsPrompt1 {
            get {
                return ResourceManager.GetString("CredentialsPrompt1", resourceCulture);
            }
        }
        
        internal static string CredentialsPrompt2 {
            get {
                return ResourceManager.GetString("CredentialsPrompt2", resourceCulture);
            }
        }
        
        internal static string FullNameLabel {
            get {
                return ResourceManager.GetString("FullNameLabel", resourceCulture);
            }
        }
        
        internal static string CreateAccountButton {
            get {
                return ResourceManager.GetString("CreateAccountButton", resourceCulture);
            }
        }
        
        internal static string OrRegisterWith {
            get {
                return ResourceManager.GetString("OrRegisterWith", resourceCulture);
            }
        }
        
        internal static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        internal static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        internal static string ForgotPageTitle {
            get {
                return ResourceManager.GetString("ForgotPageTitle", resourceCulture);
            }
        }
        
        internal static string ForgotPageDescription1 {
            get {
                return ResourceManager.GetString("ForgotPageDescription1", resourceCulture);
            }
        }
        
        internal static string ForgotPageDescription2 {
            get {
                return ResourceManager.GetString("ForgotPageDescription2", resourceCulture);
            }
        }
        
        internal static string ResetPasswordButtonText {
            get {
                return ResourceManager.GetString("ResetPasswordButtonText", resourceCulture);
            }
        }
        
        internal static string VerifyAccountTitle {
            get {
                return ResourceManager.GetString("VerifyAccountTitle", resourceCulture);
            }
        }
        
        internal static string VerifyAccountDescription1 {
            get {
                return ResourceManager.GetString("VerifyAccountDescription1", resourceCulture);
            }
        }
        
        internal static string VerifyAccountDescription2 {
            get {
                return ResourceManager.GetString("VerifyAccountDescription2", resourceCulture);
            }
        }
        
        internal static string ResendButtonText {
            get {
                return ResourceManager.GetString("ResendButtonText", resourceCulture);
            }
        }
        
        internal static string VerificationFailedTitle {
            get {
                return ResourceManager.GetString("VerificationFailedTitle", resourceCulture);
            }
        }
        
        internal static string VerificationFailedMessage {
            get {
                return ResourceManager.GetString("VerificationFailedMessage", resourceCulture);
            }
        }
        
        internal static string AccountExistsTitle {
            get {
                return ResourceManager.GetString("AccountExistsTitle", resourceCulture);
            }
        }
        
        internal static string AccountExistsMessage {
            get {
                return ResourceManager.GetString("AccountExistsMessage", resourceCulture);
            }
        }
        
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        internal static string InvalidEmailOrPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidEmailOrPasswordMessage", resourceCulture);
            }
        }
        
        internal static string EmailNotConfirmedMessage {
            get {
                return ResourceManager.GetString("EmailNotConfirmedMessage", resourceCulture);
            }
        }
        
        internal static string ResetEmailSentTitle {
            get {
                return ResourceManager.GetString("ResetEmailSentTitle", resourceCulture);
            }
        }
        
        internal static string ResetEmailSentMessage {
            get {
                return ResourceManager.GetString("ResetEmailSentMessage", resourceCulture);
            }
        }
        
        internal static string ResetEmailErrorTitle {
            get {
                return ResourceManager.GetString("ResetEmailErrorTitle", resourceCulture);
            }
        }
        
        internal static string ResetEmailErrorMessage {
            get {
                return ResourceManager.GetString("ResetEmailErrorMessage", resourceCulture);
            }
        }
        
        internal static string SelectionRequired {
            get {
                return ResourceManager.GetString("SelectionRequired", resourceCulture);
            }
        }
        
        internal static string WeightRequired {
            get {
                return ResourceManager.GetString("WeightRequired", resourceCulture);
            }
        }
        
        internal static string AgeRequired {
            get {
                return ResourceManager.GetString("AgeRequired", resourceCulture);
            }
        }
        
        internal static string FitnessLevelTitle {
            get {
                return ResourceManager.GetString("FitnessLevelTitle", resourceCulture);
            }
        }
        
        internal static string AgeTitle {
            get {
                return ResourceManager.GetString("AgeTitle", resourceCulture);
            }
        }
        
        internal static string DesiredWeightTitle {
            get {
                return ResourceManager.GetString("DesiredWeightTitle", resourceCulture);
            }
        }
        
        internal static string GoalTitle {
            get {
                return ResourceManager.GetString("GoalTitle", resourceCulture);
            }
        }
        
        internal static string HeightTitle {
            get {
                return ResourceManager.GetString("HeightTitle", resourceCulture);
            }
        }
        
        internal static string FavoriteTitle {
            get {
                return ResourceManager.GetString("FavoriteTitle", resourceCulture);
            }
        }
        
        internal static string CurrentWeightTitle {
            get {
                return ResourceManager.GetString("CurrentWeightTitle", resourceCulture);
            }
        }
        
        internal static string LevelRequired {
            get {
                return ResourceManager.GetString("LevelRequired", resourceCulture);
            }
        }
        
        internal static string NextStepText {
            get {
                return ResourceManager.GetString("NextStepText", resourceCulture);
            }
        }
        
        internal static string FinishStepText {
            get {
                return ResourceManager.GetString("FinishStepText", resourceCulture);
            }
        }
        
        internal static string BeginnerText {
            get {
                return ResourceManager.GetString("BeginnerText", resourceCulture);
            }
        }
        
        internal static string IntermediateText {
            get {
                return ResourceManager.GetString("IntermediateText", resourceCulture);
            }
        }
        
        internal static string AdvancedText {
            get {
                return ResourceManager.GetString("AdvancedText", resourceCulture);
            }
        }
        
        internal static string WeightLossText {
            get {
                return ResourceManager.GetString("WeightLossText", resourceCulture);
            }
        }
        
        internal static string GainMuscleText {
            get {
                return ResourceManager.GetString("GainMuscleText", resourceCulture);
            }
        }
        
        internal static string ImproveFitnessText {
            get {
                return ResourceManager.GetString("ImproveFitnessText", resourceCulture);
            }
        }
        
        internal static string GoalRequired {
            get {
                return ResourceManager.GetString("GoalRequired", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        internal static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        internal static string MyFavorites {
            get {
                return ResourceManager.GetString("MyFavorites", resourceCulture);
            }
        }
        
        internal static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        internal static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        internal static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        internal static string SelectYourGoal {
            get {
                return ResourceManager.GetString("SelectYourGoal", resourceCulture);
            }
        }
        
        internal static string StartExercise {
            get {
                return ResourceManager.GetString("StartExercise", resourceCulture);
            }
        }
        
        internal static string BattleStretchTraining {
            get {
                return ResourceManager.GetString("BattleStretchTraining", resourceCulture);
            }
        }
        
        internal static string FitYoungWomanDoing {
            get {
                return ResourceManager.GetString("FitYoungWomanDoing", resourceCulture);
            }
        }
        
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        internal static string HelloTextMainPage {
            get {
                return ResourceManager.GetString("HelloTextMainPage", resourceCulture);
            }
        }
        
        internal static string GoodMorningText {
            get {
                return ResourceManager.GetString("GoodMorningText", resourceCulture);
            }
        }
    }
}
